### ISSUE TITLE
エコキュートと電気錠は対応できますか？

### ISSUE THREAD

**Issue by grandevice** [hamkichi/homebridge-echonet-lite-eolia#4]
はじめまして、大変便利に使わせていただいております。

Panasonic eoliaは
CF-TC7b —— CF-TA9でこのプラグインが使用できますが、同様にechonetliteの

エコキュート
CF-TC7b —— CF-TA9c

電気錠
LANまたは無線LAN ——— HF-JA1-W

の対応は可能でしょうか？よろしくお願いいたします。echonetの規格書をみてcodeでできるところまではわかったのですが、、、

**Comment by hamkichi** [comment]
完全に放置してしまっており、今更の回答となり恐縮です。。。
あくまで個人使用のために作成したものということと、テストができないため対応の予定はありません。申し訳ありませんが、必要に応じてForkして作成いただくようお願いします。
